// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2EtJTTgKAOuGarmKTK5JrVdMLPgRhyk',
    appId: '1:40491801389:web:410a78a5387f53ab45d1a4',
    messagingSenderId: '40491801389',
    projectId: 'tikidown-6ce8d',
    authDomain: 'tikidown-6ce8d.firebaseapp.com',
    storageBucket: 'tikidown-6ce8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKzTAfeva1TPiNCZSCyT2mR0PREVArmnY',
    appId: '1:40491801389:android:698172527b6602f645d1a4',
    messagingSenderId: '40491801389',
    projectId: 'tikidown-6ce8d',
    storageBucket: 'tikidown-6ce8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0UwXDykcA8GRezqUgp_09vrymCzsEDl0',
    appId: '1:40491801389:ios:d1432e539d7d440945d1a4',
    messagingSenderId: '40491801389',
    projectId: 'tikidown-6ce8d',
    storageBucket: 'tikidown-6ce8d.appspot.com',
    iosBundleId: 'inc.dima.tikidown.tikidown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0UwXDykcA8GRezqUgp_09vrymCzsEDl0',
    appId: '1:40491801389:ios:b6d189020a3d3ffc45d1a4',
    messagingSenderId: '40491801389',
    projectId: 'tikidown-6ce8d',
    storageBucket: 'tikidown-6ce8d.appspot.com',
    iosBundleId: 'inc.dima.tikidown.tikidown.RunnerTests',
  );
}
